# This is a basic workflow to help you get started with Actions

name: Powershell Multiple Stuff

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    job1:
        name: job1
                              # The type of runner that the job will run on
        runs-on: self-hosted
        steps:
        - name: Step One Checkout
                                # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Step Two Run Two Scripts
          run: |
            powershell .\stageone.ps1
            powershell .\stagTwo.ps1
          shell: powershell

    job2:
        name: job2
        runs-on: self-hosted
        steps:
        - name: Step Three echo computername
          run: echo %computername%  
        - name: Step Four get environment variables
          run:  "get-childitem ENV: | sort-object Name"

