# This is a basic workflow to help you get started with Actions

name: Powershell Multiple Stuff

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    job1:
        name: job1
        runs-on: self-hosted
        steps:
            - name: Step One Checkout
              uses: actions/checkout@v2
            - name: Step Two Run Two Scripts
              run: |
                powershell .\stageone.ps1
                powershell .\stageTwo.ps1
              shell: powershell

    job2:
        name: job2
        runs-on: self-hosted
        steps:
            - name: Step Three Checkout
              uses: actions/checkout@v2
            - name: Step Four get environment variables
              run:  "get-childitem ENV: | sort-object Name"

    job3:
        name: job3
        needs:  [job1,job2]
        runs-on: self-hosted
        steps:
            - name: Step Four Checkout
              uses: actions/checkout@v2
            - name: Step Five get service WINRM
              run:  "get-service WINRM"
